# Generated by Django 6.1 on 2026-08-18 23:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada'), ('completada', 'Completada')], db_index=True, default='activa', max_length=12, verbose_name='Estado')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio ponderado de todas las entregas calificadas.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota final')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripcion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
