# Generated by Django 6.1 on 2026-08-18 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_como_estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['estudiante', 'estado'], name='idx_inscr_est_estado'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['curso', 'estado'], name='idx_inscr_curso_estado'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('curso', 'estudiante'), name='uq_inscripcion_curso_estudiante'),
        ),
    ]
