# Generated by Django 6.1 on 2026-08-27 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_total_asignaciones'),
        ('inscripciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscripcion',
            name='uq_inscripcion_curso_estudiante',
        ),
        migrations.RenameIndex(
            model_name='inscripcion',
            new_name='idx_inscr_estudiante_estado',
            old_name='idx_inscr_est_estado',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobacion'), ('activa', 'Activa'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada'), ('completada', 'Completada')], db_index=True, default='pendiente', max_length=12, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('curso', 'estudiante'), name='unique_inscripcion_curso_estudiante'),
        ),
    ]
