# Generated by Django 6.1 on 2026-08-18 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('descripcion', models.TextField(help_text='Instrucciones detalladas de la asignacion.', verbose_name='Descripcion')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('quiz', 'Quiz')], db_index=True, default='tarea', max_length=10, verbose_name='Tipo')),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=100.0, help_text='Puntuacion maxima posible para esta asignacion.', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Valor maximo')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha limite de entrega')),
                ('permite_entrega_tardia', models.BooleanField(default=False, verbose_name='Permite entrega tardia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Respuesta, solucion o enlace al trabajo entregado.', verbose_name='Contenido de la entrega')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('calificada', 'Calificada'), ('devuelta', 'Devuelta para revision')], db_index=True, default='borrador', max_length=12, verbose_name='Estado')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Nota asignada por el profesor. No puede superar el valor maximo.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calificacion')),
                ('retroalimentacion', models.TextField(blank=True, verbose_name='Retroalimentacion del profesor')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de calificacion')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
