# Generated by Django 6.1 on 2026-08-18 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas_como_estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['curso', 'tipo'], name='idx_asignacion_curso_tipo'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['curso', 'fecha_entrega'], name='idx_asignacion_curso_fecha'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['asignacion', 'estado'], name='idx_entrega_asignacion_estado'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['estudiante', 'estado'], name='idx_entrega_estudiante_estado'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('asignacion', 'estudiante'), name='uq_entrega_asignacion_estudiante'),
        ),
    ]
