# Generated by Django 6.1 on 2026-08-22 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Porcentaje del peso de esta asignacion en la nota final del curso (ej: 25.00%).', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de la nota final (%)'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Puntaje maximo posible para calificar esta asignacion (ej: 20.00 pts).', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Puntaje maximo (Nota maxima)'),
        ),
    ]
