# Generated by Django 6.1 on 2026-08-23 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Correo asociado a la solicitud para control de reintentos.', max_length=254, verbose_name='Correo electronico')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=15, verbose_name='Estado de la solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolucion')),
                ('motivo_rechazo', models.TextField(blank=True, default='', verbose_name='Motivo de rechazo o comentarios')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Profesor',
                'verbose_name_plural': 'Solicitudes de Profesores',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
