# Generated by Django 6.1 on 2026-08-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Si tiene fecha, el usuario no puede crear cursos hasta entonces.', null=True, verbose_name='Bloqueado hasta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos_creacion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rastrea cuántas veces intentó crear cursos evadiendo el cooldown.', verbose_name='Intentos fallidos de creacion'),
        ),
    ]
