# Generated by Django 6.1 on 2026-08-18 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('codigo', models.CharField(help_text='Codigo unico de identificacion del curso (ej. MAT-101).', max_length=20, unique=True, verbose_name='Codigo del curso')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=10, verbose_name='Estado')),
                ('capacidad_maxima', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Capacidad maxima de estudiantes')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
