# Generated by Django 6.1 on 2026-08-18 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_como_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['profesor', 'estado'], name='idx_curso_profesor_estado'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='idx_curso_estado_inicio'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='chk_curso_fecha_fin_mayor_inicio'),
        ),
    ]
