# Generated by Django 6.1 on 2026-08-22 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='total_asignaciones',
            field=models.PositiveSmallIntegerField(default=4, help_text='Cantidad total de asignaciones planificadas para calcular el progreso y promedios del curso.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Total de asignaciones planificadas'),
        ),
    ]
