# Generated by Django 6.1 on 2026-08-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_total_asignaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobacion'), ('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=10, verbose_name='Estado'),
        ),
    ]
